#!/bin/bash -e

# If there's no action folder, assume that we're being run from curl
if [[ ! -d actions ]]; then
    pushd ~
    git clone https://github.com/dburkart/dotfiles.git .dotfiles
    cd .dotfiles
    ./setup
    code=$?
    popd
    exit $code
fi

source ./lib/environment.sh

if [[ "$PLATFORM" == "unknown" ]]; then
    echo "Unsupported platform, exiting."
    exit 255
fi

for action in $(ls actions); do
    echo ""
    echo "### Running action $action..."
    ./actions/$action
    code=$?

    if [[ "$code" != "0" ]]; then
        echo "### Action $action failed, stopping."
        exit $code
    fi
done
