#!/bin/bash -e

# If there's no action folder, assume that we're being run from curl
if [[ ! -d actions ]]; then
    pushd ~
    git clone https://github.com/dburkart/dotfiles.git .dotfiles
    cd .dotfiles
    ./setup
    popd
    exit 0
fi

for action in $(ls actions); do
    echo ""
    echo "### Running action $action..."
    ./actions/$action
done
